name: generator

environment:
  sdk: '>=2.13.0-0 <3.0.0'

dependencies:
  alfred:
    git:
      url: https://github.com/modulovalue/alfred.git
      ref: 37d1706

dev_dependencies:
  extra_pedantic: ^1.5.0
